[package]
name = "cargo-typegraph"
version = "0.1.0"
edition = "2024"
description = "Generate Graphviz DOT dependency graphs for Rust types."
readme = "README.md"
license = "CC0-1.0"
keywords = ["cargo", "graphviz", "rustdoc", "types"]
categories = ["development-tools", "development-tools::cargo-plugins", "visualization"]
repository = "https://github.com/dpottavio/cargo-typegraph"

[dependencies]
serde_json = "1"
